document page created
tcet-opensource/tcet-website pull request #41
Opened 2023-06-23 17:05 UTC by Horror26

2023-06-24 12:58 UTC, JayeshVP24 requested changes

2023-06-24 12:58 UTC, JayeshVP24 commented on src/components/About/Documention/Document.tsx
> +            <img src={img} alt="test" />
give fixed width

2023-06-24 12:58 UTC, JayeshVP24 commented on src/components/About/Documention/index.astro
> +        <div
unnecessary two main divs. merge div at line 16 and div at line 18

2023-06-24 12:58 UTC, JayeshVP24 commented on src/components/About/Documention/index.astro
> +            NIRF DATA
make this more dynamic
title and color of one section can also come from array of objects itself.
example 
const data = 
```
const data = [
   {
        title: "NIRF DATA".
        color: "#667085",
        files: [
            {
                title: "sometitle",
                link: "somelink"
            },
            ....
        ]
   },
   .....
]
```

You will need to map twice.

2023-06-24 15:59 UTC, JayeshVP24 commented on src/components/About/Documention/index.astro
> +            NIRF DATA
you will have problems with tailwind colors when doing like this
use inline css with javascript variables for this

2023-06-27 15:05 UTC, JayeshVP24 requested changes
last changes

2023-06-27 15:05 UTC, JayeshVP24 commented on src/components/About/Documention/Document.tsx
> +          <img src={img} alt="test" /> </div>
give this a fixed width, remove give proper alt

2023-06-27 15:05 UTC, JayeshVP24 commented on src/components/About/Documention/index.astro
> +<main class="flex flex-col">
give `p-4 lg:p-16`
move all this code to pages/about/documentation.astro

2023-06-29 16:16 UTC, kamalika0363 approved these changes
Approved

2023-06-29 16:17 UTC, merged