31 recognition and award
tcet-opensource/tcet-website pull request #43
Opened 2023-06-23 20:39 UTC by Bhargav-44

Added the recognition and reward page

2023-06-24 13:53 UTC, JayeshVP24 requested changes
Your margin tops across all headings are not enough for large screens. increase it for large screens

2023-06-24 13:53 UTC, JayeshVP24 commented on src/components/About/RecognitionAward/index.astro
> +<section class="px-5">
remove px-5
add `p-4 lg:p-16`

2023-06-24 13:53 UTC, JayeshVP24 commented on src/pages/about/recognition-and-award.astro
> +---
rename recognition-and-award -> recognition-and-awards
awards is plural

2023-06-24 15:40 UTC, JayeshVP24 requested changes

2023-06-24 15:40 UTC, JayeshVP24 commented on src/components/About/RecognitionAward/index.astro
> +<section class="p-4 lg:p-16">
You have made proper divs.
But you added pt pb everywhere and one spacing change requires us to change many lines of code. Tailwind has something called space-y space-x.
Read the tailwind docs. and u can remove all singular padding and use space so spacing is consistent all over the page

2023-06-24 15:40 UTC, JayeshVP24 commented on src/components/About/RecognitionAward/index.astro
> +---
Also this whole page is unnecessary. It beats the point of components. Move all this code to pages/about/recognition-and-awards.astro page

2023-06-24 16:30 UTC, JayeshVP24 requested changes

2023-06-24 16:30 UTC, JayeshVP24 commented on src/pages/about/recognition-and-awards.astro
> +		<section class="p-4 lg:p-16 space-y-4 lg:space-y-10">
remove section, you coded a whole page not a section.
your sections should be on  the divs

2023-06-24 16:30 UTC, JayeshVP24 commented on src/pages/about/recognition-and-awards.astro
> +				class="h-full w-full flex flex-wrap m-auto lg:flex-nowrap items-start justify-center mt-6"
remove lg:no-wrap

2023-06-27 15:09 UTC, JayeshVP24 requested changes

2023-06-27 15:09 UTC, JayeshVP24 commented on src/pages/about/recognition-and-awards.astro
> +		<div class="p-4 lg:p-16 space-y-4 lg:space-y-10">
remove this div and move the class to main

2023-06-29 16:13 UTC, kamalika0363 approved these changes
Approved

2023-06-29 16:13 UTC, merged