39-Life@TCET Home Page
tcet-opensource/tcet-website pull request #44
Opened 2023-06-24 14:11 UTC by Alstudd

Created components and pages for Life@TCET Home page

2023-06-24 15:46 UTC, JayeshVP24 requested changes

2023-06-24 15:46 UTC, JayeshVP24 commented on src/styles/life-at-tcet-home.css
> +.main-section {
never give fix width and heights

2023-06-24 15:46 UTC, JayeshVP24 commented on src/styles/life-at-tcet-home.css
> +.main-section {
take your time, move to tailwindCSS

2023-06-27 15:18 UTC, JayeshVP24 requested changes

2023-06-27 15:18 UTC, JayeshVP24 commented on src/pages/life-at-tcet/index.astro
> +        <h1 class="font-title sm:text-center text-4xl font-normal leading-[44px] tracking-[-0.02em] text-left text-[#101828">Life@TCET</h1>
u forgot the bracked at text color

2023-06-27 15:18 UTC, JayeshVP24 commented on src/pages/life-at-tcet/index.astro
> +        <ul class="pl-[30px]">
remove pixel and use tailwind unit
pl-6

2023-06-27 15:18 UTC, JayeshVP24 commented on src/pages/life-at-tcet/index.astro
> +            <li style="list-style-type: disc;" class="sm:w-[320px] text-base font-medium leading-6 tracking-normal text-left text-[#757575] w-[750px]">TCET Acheivements:A Mark of Quality Education</l
remove w-[320px]
never use fixed widths unless absolutely necessary such as with images
remove w-[750px]

2023-06-27 15:18 UTC, JayeshVP24 commented on src/pages/life-at-tcet/index.astro
> +            <li style="list-style-type: disc;" class="sm:w-[320px] text-base font-medium leading-6 tracking-normal text-left text-[#757575] w-[750px]">Institute is NAAC accredited with grade “A” in 1
remove width

2023-06-27 15:18 UTC, JayeshVP24 commented on src/pages/life-at-tcet/index.astro
> +            <li style="list-style-type: disc;" class="sm:w-[320px] text-base font-medium leading-6 tracking-normal text-left text-[#757575] w-[750px]">Institute is ranked among top 200 colleges in th
remove width

2023-06-27 17:12 UTC, JayeshVP24 requested changes

2023-06-27 17:12 UTC, JayeshVP24 commented on src/pages/life-at-tcet/index.astro
> +    <div class="sm:items-center flex flex-col gap-4 pl-3 rounded-lg">
remove pl-3 and add `p-4 lg:p-16`

2023-06-27 17:12 UTC, JayeshVP24 commented on src/pages/life-at-tcet/index.astro
> +        <ThirdCards />
text-left is default ig, u can remove it

2023-06-27 17:12 UTC, JayeshVP24 commented on src/pages/life-at-tcet/index.astro
> +        <SecondCards />
wrap in one <section>

2023-06-27 17:12 UTC, JayeshVP24 commented on src/pages/life-at-tcet/index.astro
> +        </ul>
wrap in one <section>

2023-06-27 17:12 UTC, JayeshVP24 commented on src/pages/life-at-tcet/index.astro
> +        <ThirdCards />
wrap in one <section>

2023-06-29 16:11 UTC, kamalika0363 approved these changes
Approved Changes

2023-06-29 16:11 UTC, merged