[FEAT] Message component
tcet-opensource/tcet-website pull request #50
Opened 2023-06-25 16:59 UTC by yv2003

2023-06-25 20:24 UTC, JayeshVP24 requested changes
Also check the notion file pinned in frontend chat. wait
https://tcet-opensource.notion.site/TCET-Mumbai-Docs-f92526652a9a4facbc4b74d0ffe1a612?pvs=4
here, 
the file names of all message pages should be same as the href in this

2023-06-25 20:24 UTC, JayeshVP24 commented on src/components/About/Message/index.astro
> +    <div class="pt-2.5 pr-2.5 pl-2.5  font-normal text-4xl leading-10 gap-10 tracking-tight" style="font-family: Fraunces">{title}</div>
remove style="font-famil....
add tailwind class `font-title`
font-title is fraunces

2023-06-25 20:24 UTC, JayeshVP24 commented on src/components/About/Message/index.astro
> +                class="font-[Inter] text-base font-normal text-[#475467] first-line:tracking-widest first-letter:text-4xl first-letter:font-bold first-letter:text-[#475467] first-letter:mr-1 first-le
remove font Inter, remove first line tracking widest, remove first letter text -[#... , remove first letter float

2023-06-25 20:24 UTC, JayeshVP24 commented on src/components/About/Message/index.astro
> +            <p class="pt-2 font-[Inter] text-xl font-[600] text-[#475467] italic">
remove font inter
inter is default

2023-06-25 20:24 UTC, JayeshVP24 commented on src/components/About/Message/index.astro
> +            <p class="pt-2 font-[Inter] text-xl font-[600] text-[#475467] italic">
remove italic, check figma properly. Our aim is to make it as close to figma as possible

2023-06-25 20:24 UTC, JayeshVP24 commented on src/components/About/Message/index.astro
> +<style>
delete all style tag full

2023-06-25 20:24 UTC, JayeshVP24 commented on src/components/About/Message/index.astro
> +<link rel="preconnect" href="https://fonts.googleapis.com" />
remove all this links of fonts. I have added font in layout already

2023-06-27 15:35 UTC, JayeshVP24 requested changes

2023-06-27 15:35 UTC, JayeshVP24 commented on src/components/About/Message/index.astro
> +/>
remove these lines

2023-06-29 15:41 UTC, kamalika0363 approved these changes
LGTM

2023-06-29 15:41 UTC, merged