[FEAT] Notification pop up is completed
tcet-opensource/tcet-website pull request #51
Opened 2023-06-25 17:07 UTC by RohanDarade

Currently the position of popup is set fixed and height is auto

2023-06-25 20:29 UTC, JayeshVP24 requested changes

2023-06-25 20:29 UTC, JayeshVP24 commented on src/components/Notification/Notification.jsx
> +        <div className="fixed top-56 z-10 right-0 mx-8 rounded-lg">
give white background and radius full , that bell  is hard to find. also add hover effects

2023-06-25 20:29 UTC, JayeshVP24 commented on src/components/Notification/Notification.jsx
> +              <div className="border-t-[1px] px-6 flex flex-row py-3 min-h-fit justify-start border-[#E4E7EC] items-baseline">
add hover effects here as well

border-t is equivalent to border-t-[1px[

2023-06-25 20:29 UTC, JayeshVP24 commented on src/layouts/Layout.astro
> +	<body class="overflow-x-hidden max-w-screen mx-auto" >
why did u do this? can u explain?

2023-06-26 04:25 UTC, RohanDarade commented on src/layouts/Layout.astro
> +	<body class="overflow-x-hidden max-w-screen mx-auto" >
I've no clue when did this happended, as far as ik layout and certified by section me I didn't made any changes

2023-06-26 04:25 UTC, RohanDarade commented on src/layouts/Layout.astro
> +	<body class="overflow-x-hidden max-w-screen mx-auto" >
<img width="479" alt="image" src="https://github.com/tcet-opensource/tcet-website/assets/72266465/83531743-0add-4d4e-b8a9-b2b6227edefd">
This was the ss of the git status i did just after git add

2023-06-27 15:37 UTC, JayeshVP24 submitted a review, later dismissed

2023-06-27 15:37 UTC, JayeshVP24 commented on src/components/Notification/Notification.jsx
> +              className="bg-white p-3 rounded-full hover:drop-shadow-xl"
give shadow-lg or xl maybe and change bg color on hover

2023-06-29 18:29 UTC, kamalika0363 approved these changes

2023-06-29 18:30 UTC, merged